project:
  type: default

bibliography: assets/bib/references.bib
csl: assets/bib/apa.csl

filters:
  - cite-quote

format:
  gfm:
    variant: +yaml_metadata_block
    wrap: none
    toc: false

editor: visual

execute:
  freeze: true
