project:
  type: website
  output-dir: docs

website:
  title: "How to Science"
  page-navigation: true
  reader-mode: true
  navbar:
    background: dark
    foreground: light
    pinned: false
    collapse: true
    collapse-below: sm # sm, md, lg, xl, or xxl
    logo: assets/img/logo.png
    left:
      - text: "About"
        href: index.qmd
      - text: "Survey Design"
        href: chapters/surveys/index.qmd
      - text: "Statistics"
        href: chapters/statistics/index.qmd

  sidebar:
    - id: surveys
      title: "Survey Design"
      style: "docked" # floating, docked
      collapse-level: 2
      align: left
      contents:
        - chapters/surveys/index.qmd
        - chapters/surveys/item-development.qmd
        - chapters/surveys/response-options.qmd
        - chapters/surveys/recommended-reading.qmd

    - id: statistics
      title: "Statistics"
      contents:
        - chapters/statistics/index.qmd
        - section: "Factor Analysis"
          contents:
            - chapters/statistics/EFA.qmd
            - chapters/statistics/CFA.qmd

format:
  html:
    theme: cosmo
    css: assets/css/styles.css

editor: visual
