project:
  type: website
  output-dir: docs

website:
  title: "How to Science"
  page-navigation: true
  reader-mode: true
  repo-url: https://github.com/willemsleegers/how-to-science/
  repo-actions: [edit, issue]
  navbar:
    background: light
    pinned: false
    collapse: true
    collapse-below: sm # sm, md, lg, xl, or xxl
    logo: assets/img/logo.png
    left:
      - text: "About"
        href: index.qmd
      - text: "Survey Design"
        href: sections/surveys/index.qmd
      - text: "Statistics"
        href: sections/statistics/index.qmd

  sidebar:
    - id: surveys
      title: "Survey Design"
      style: "floating" # floating, docked
      collapse-level: 2
      align: left
      contents:
        - sections/surveys/index.qmd
        - sections/surveys/item-development.qmd
        - sections/surveys/response-options.qmd
        - sections/surveys/recommended-reading.qmd

    - id: statistics
      title: "Statistics"
      contents:
        - sections/statistics/index.qmd
        - section: "Factor Analysis"
          contents:
            - sections/statistics/factor-analysis/EFA.qmd
            - sections/statistics/factor-analysis/CFA.qmd
            - sections/statistics/factor-analysis/r-packages.qmd
            - sections/statistics/factor-analysis/examples.qmd
            - sections/statistics/factor-analysis/recommended-reading.qmd

format:
  html:
    theme: cosmo
    css: assets/css/styles.css
    csl: assets/bib/apa.csl

editor: visual
