project:
  type: default

bibliography: assets/bib/references.bib
csl: assets/bib/apa.csl

filters:
  - cite-quote
  - assets/filters/cite-wrap.lua

format:
  gfm:
    variant: +yaml_metadata_block
    wrap: none
    toc: false
    fig-format: svg


editor: source

execute:
  freeze: true
