---
title: "Response Options"
toc: true
bibliography: references.bib
---

::: callout-warning
This chapter is still a work in progress.
:::

There are several decisions to make that involve response options. How many response options should you use? Should you use an even or odd number of response options? Should you label them? This section contains a summary of best practices that one can use to address these questions.

## Number of Response Options

The question of how many response options to use centers around two main concerns. The first is that more options means you can obtain a more fine-grained assessment of the characteristic that is being evaluated (e.g., attitude). In other words, your assessment is more precise. However, the question is how the number of options affects the reliability and the validity of the measurement. With more options, it becomes more difficult for people to distinguish between the different options (e.g., is "Strongly agree" reliably different from "Very strongly agree"?).

Table 1 shows an overview of various studies in which the topic of response options was addressed. The studies vary in many ways, so the final conclusion should be a holistic interpretation of the results, rather than a simple tallying of the results. Note also that only empirical studies are included and not simulation studies. Simulation studies seem limited because they cannot address the plausible psychological limitation of people being unable to distinguish between many options.

+----------------+------------------------------------+---------------------------------+
| Source         | Comparisons                        | Conclusion                      |
+================+====================================+=================================+
| @donnellan2020 | 2- to 7-, and 11-point Likert      | 5-point Likert or higher        |
+----------------+------------------------------------+---------------------------------+
| @simms2019     | 2- to 11-point Likert + VAS        | 6-point Likert                  |
+----------------+------------------------------------+---------------------------------+
| @sung2018      | 5-point Likert and VAS-RRP         | VAS-RPP                         |
+----------------+------------------------------------+---------------------------------+
| @cox2017       | 2- and 4-point Likert              | Mixed                           |
+----------------+------------------------------------+---------------------------------+
| @lewis2017     | 7-, 11-point Likert and VAS        | No difference                   |
+----------------+------------------------------------+---------------------------------+
| @kuhlmann2017  | 5-point Likert and VAS             | No difference                   |
+----------------+------------------------------------+---------------------------------+
| @hilbert2016   | 2- and 5-point and VAS             | It depends                      |
+----------------+------------------------------------+---------------------------------+
| @capik2015     | 2- and 5-point Likert              | No difference                   |
+----------------+------------------------------------+---------------------------------+
| @eutsler2015   | 5-, 7-, 9-, and 11-point Likert    | 7-point Likert                  |
+----------------+------------------------------------+---------------------------------+
| @finn2015      | 2- and 4-point Likert              | 4-point Likert                  |
+----------------+------------------------------------+---------------------------------+
| @revilla2014   | 5-, 7-, 11-point Likert            | 5-point Likert                  |
+----------------+------------------------------------+---------------------------------+
| @cox2012       | 2- and 4-point Likert              | 4-point Likert                  |
+----------------+------------------------------------+---------------------------------+
| @janhunen2012  | 7-point Likert and 30-point VAR    | VAR                             |
+----------------+------------------------------------+---------------------------------+
| @dawes2008     | 5-, 7-, and 10-point Likert        | No difference                   |
+----------------+------------------------------------+---------------------------------+
| @weng2004      | 3- to 9-point Likert               | 5-point or higher               |
+----------------+------------------------------------+---------------------------------+
| @preston2000   | 2- to 11-point Likert and VAS      | 7-, 9-, or 10-point Likert      |
+----------------+------------------------------------+---------------------------------+
| @alwin1997     | 7- and 11-point Likert             | 11-point Likert                 |
+----------------+------------------------------------+---------------------------------+
| @jaeschke1990  | 7-point Likert and VAS             | No difference\                  |
|                |                                    | (slightly favor 7-point Likert) |
+----------------+------------------------------------+---------------------------------+
| @flamer1983    | 2- and 9-point Likert              | 9-point Likert                  |
+----------------+------------------------------------+---------------------------------+
| @matell1971    | 2-point to 18-point Likert         | No difference                   |
+----------------+------------------------------------+---------------------------------+
| @bendig1954    | 2-, 3-, 5-, 7-, and 9-point Likert | No difference\                  |
|                |                                    | (maybe 3-point or higher)       |
+----------------+------------------------------------+---------------------------------+

: Table 1: Overview of empirical studies on the topic of response options.

There are also several review papers on the topic. @krosnick2010 suggest that 7-point Likert scales are probably optimal. @lietz2010 concludes a desirable Likert-scale consists of 5 to 8 response options. Similarly, @coxiii1980 recommends to use between 5 and 9 response options. @symonds1924, in 1924, claims the optimum number is 7. @gehlbach2011 recommends using 5-points for unipolar items and 7-point for biopolar items.

Besides psychometric properties it may also be worth taking into account respondent preference. This involves ease of use of the scale and whether the response options allow for sufficient variation for respondents to express their view. @preston2000 found that respondents found scales with 5, 7, and 10 points easy to use (compared to fewer options and a VAS) and that they preferred scales with more response options to allow them to express themselves (7 or more). Other studies also show that respondents favor more options [@cox2017].

Note that if time is of the essence, fewer response options are preferred.

Another relevant factor is whether the scale is bipolar or unipolar. Bipolar scales are symmetrical which means the number of options naturally increase as they need to match both sides of the spectrum. Unipolar items are only about one side, usually ranging from the absence of something to the presence of something (to a certain degree). Since it is harder to label a larger number of options for a unipolar scale, the number of options are likely to be smaller.

**Conclusion**: It appears that few response options (2 or 3) should definitely be avoided. More response options therefore seems better, but benefits seem to quickly level off. Given other concerns, such as ease of use and interpretability, a 7-point Likert scale seems to be preferred for bipolar scales and a 5-point Likert scale for unipolar scales.

## Odd vs. Even Response Options

The middle option of a scale can have an ambiguous meaning. Participants may use it to indicate a moderate standing on the issue (Rugg and Cantril, 1944), a lack of an opinion (Nadler, Weston, and Voyles, 2014), ambivalence (Klopfer and Madden, 1980; Schaeﬀer and Presser, 2003; Nadler, Weston, and Voyles, 2014), indifference (Schaeﬀer and Presser, 2003; Nadler, Weston, and Voyles, 2014), uncertainty (Baka, Figgou, and Triga, 2012; Nadler, Weston, and Voyles, 2014), confusion, or to signal context dependence (e.g., "it depends" or disputing the question, see Baka, Figgou, and Triga, 2012).

The middle option may also be used for certain response styles, such as socially desirable responding (Sturgis, Roberts, and Smith, 2012) or satisficing (Krosnick, 1991), although there is not much research showing it actually leads to satisficing @wang2020.

Af a middle alternative is explicitly oﬀered, the proportion endorsing it increases dramatically (e.g. Ayidiya & McClendon, 1990; Bishop, 1987; Bishop, Hippler, Schwarz, & Strack, 1988; Kalton, Collins, & Brook, 1978; Kalton, Roberts, & Holt, 1980; Rugg & Cantril, 1944).

Some studies show that not including a middle option decreases validity and increases measurement error (O'Muircheartaigh, Krosnick, and Helic, 1999; Kahn, and Dhar, 2002)

Recent study on this: @wang2020

An alternative approach to this issue is to use branching. Respondents could first be asked whether they fall at the midpoint or on one side, followed by a question about their extremity on a side. This approach was found to be more reliable and valid than using a 7-point scale (Krosnick and Berent, 1993; Malhotra, Krosnick, and Thomas, 2009).

**Conclusion**: If it is possible that respondents may have a moderate view, it seems crucial for it to be possible to capture this view. Limitations of a middle option could then be addressed in other ways (e.g., clear questions).

## Response Option Labeling

There are several studies that show all response options should be labelled, rather than only labeling the end points [@weng2004; @krosnick1993].

For an example of biopolar labels for a 2- to 11-point Likert scale, see Table 1.

::: column-body-outset
| Label                      | 2-point | 3-point | 4-point | 5-point | 6-point | 7-point | 8-point | 9-point | 10-point | 11-point |
|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| Very strongly disagree     |         |         |         |         |         |         | x       | x       | x        | x        |
| Strongly disagree          |         |         | x       | x       | x       | x       | x       | x       | x        | x        |
| Disagree                   | x       | x       | x       | x       | x       | x       | x       | x       | x        | x        |
| Mostly disagree            |         |         |         |         |         |         |         |         | x        | x        |
| Slightly disagree          |         |         |         |         | x       | x       | x       | x       | x        | x        |
| Neither agree nor disagree |         | x       |         | x       |         | x       |         | x       |          | x        |
| Slightly agree             |         |         |         |         | x       | x       | x       | x       | x        | x        |
| Mostly agree               |         |         |         |         |         |         |         |         | x        | x        |
| Agree                      | x       | x       | x       | x       | x       | x       | x       | x       | x        | x        |
| Strongly agree             |         |         | x       | x       | x       | x       | x       | x       | x        | x        |
| Very strongly agree        |         |         |         |         |         |         | x       | x       | x        | x        |

: Table 1: Likert response labels from @simms2019
:::

It is also recommended to avoid agree-disagree response labels because asking respondents to rate their level of agreement is a cognitively demanding task that increases respondent error and reduces responding effort [@gehlbach2011].

**Agreement:** Strongly agree, Moderately agree, Neither agree nor disagree, Moderately disagree, Strongly disagree (another version removes the "moderately" qualifier and/or uses "neutral")

**Comparison:** Much X, Slightly X, About the same, Slightly (opposite of X), Much (opposite of X)

**Ease:** Very easy, Moderately easy, Neither easy nor difficult, Moderately difficult, Very difficult

**Expectations:** Exceeds expectations, Fully meets expectations, Does not fully meet expectations, Does not meet expectations at all

**Extent (5 pt):** A great deal (Completely, if appropriate), Considerably, Moderately, Slightly, Not at all

**Extent (4 pt):** Significantly, Moderately, Slightly, Not at all

**Frequency (no set time):** Always, Often, Occasionally, Rarely, Never

**Frequency (general):** Daily, Weekly, Monthly, Once a semester, Once a year, Never

**Frequency (based on time frame):** More than 5 times, 4 - 5 times, 2 - 3 times, 1 time, Less than 1 time, Never

**Frequency (extended):** More than once a week, Once a week, Once a month, Once a semester, Once a year, Less than once a year, Never

**Helpfulness:** Extremely helpful, Very helpful, Moderately helpful, Slightly helpful, Not at all helpful

**Importance:** Extremely important, Very important, Moderately important, Slightly important, Not at all important

**Interest:** Extremely interested, Very interested, Moderately interested, Slightly interested, Not at all interested

**Likelihood:** Very likely, Moderately likely, Neither likely nor unlikely, Moderately unlikely, Very unlikely

**Numeric Scales:** Less than #, About the same, More than \#

**Probability:** Definitely would, Probably would, Probably wouldn't, Definitely wouldn't

**Proficiency:** Beginner, Developing, Competent, Advanced, Expert (typical for Rubrics)

**Quality:** Excellent, Good, Average, Below average, Poor

**Satisfaction:** Very satisfied, Moderately satisfied, Neither satisfied nor dissatisfied, Moderately dissatisfied, Very dissatisfied (another version removes the "moderately" qualifier and/or uses "neutral")

Taken from https://baselinesupport.campuslabs.com/hc/en-us/articles/204305485-Recommended-Scales

## References
