# Data Visualization

```{r, setup, include=FALSE}
# Load packages
library(tidyverse)
library(viridis)
library(plotly)

theme_rethink <- function() {
  theme(panel.background = element_rect(fill = "gray95"))
}

colors <- c("#0B0405FF", "#291A31FF", "#3D3165FF", "#3E5095FF", "#3573A1FF", 
  "#3496A9FF", "#40B7ADFF", "#76D5AEFF", "#C4EAD0FF")
```

## Bar charts

```{r}
p <- ggplot(mpg, aes(x = class, fill = class)) +
  geom_bar() +
  scale_fill_viridis(discrete = TRUE, option = "mako") +
  theme_rethink()

ggplotly(p)
```

## Line charts

```{r}
p <- ggplot(economics, aes(x = date, y = unemploy)) + 
  geom_line(alpha = .75) +
  theme_minimal()

ggplotly(p)
```

```{r}
p <- ggplot(economics_long, aes(x = date, y = value01, 
    color = variable)) +
  geom_line() +
  scale_color_viridis(discrete = TRUE, option = "mako") +
  theme_minimal()

ggplotly(p)
```

## Scatter plots

```{r}
p <- ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_point(alpha = .75) +
  theme_minimal()

ggplotly(p)
```

```{r}
p <- ggplot(mtcars, aes(x = wt, y = mpg, color = factor(cyl))) +
  geom_point(alpha = .75) +
  scale_color_viridis_d() +
  theme_minimal()

ggplotly(p)
```
