# Factor analysis

## Exploratory factor analyses

The goal of an exploratory factor analysis (EFA) is to study the latent factors that underlie responses to a larger number of items. In other words, the goal is to *explore* the data and *reduce* the number of variables. It is a popular technique in the development and validation of assessment instruments. Unlike confirmatory factor analysis (CFA), EFA is used when there is little or no a priori justification for specifying a particular structural model. This means that there is reasonable uncertainty about the number of underlying factors and which items load on which factor. The hope is to resolve some of that uncertainty empirically.

### Principal Components vs. Factor Analysis

An important consideration is whether to use a principal components analysis (PCA) or a factor analysis.

PCA is a data reduction technique. PCA computes the analysis without regard to the underlying latent structure of the variables, using all the variance in the manifest variables. When the goal is to develop a (psychological) scale, this is likely not what you want. With PCA, the variables are themselves of interest, rather than some hypothetical latent construct. Another way of describing it is that PCA conceptualizes constructs as causally determined by the observations (Edwards & Bagozzi, 2000). Again, this is likely not what you want because this means that "principal component scores are "caused" by their indicators in much the same way that sumscores are "caused" by item scores." [@borsboom2006]. Instead, you likely want the opposite causal relationship in which a latent factor causes the indicator scores.

```{r, echo=FALSE}
library(DiagrammeR)

grViz("
digraph dot {

graph [layout = dot,
       rankdir = LR]

node [shape = square,
      color = black,
      label = '']

var1 [label = 'variable 1']
var2 [label = 'variable 2']
var3 [label = 'variable 3']
var4 [label = 'variable 4']
var5 [label = 'variable 5']
var6 [label = 'variable 6']  
var7 [label = 'variable 7']  
var8 [label = 'variable 8']
    
node [label = 'component A']
comp1

node [label = 'component B']
comp2

edge [color = black, minlen = 3]
{var1 var2 var3 var4} -> comp1
{var5 var6 var7 var8} -> comp2
}")
```

While common factor analysis assumes that total variance can be partitioned into common and unique variance, PCA assumes that there common variances takes up all of total variance. This means that PCA assumes that all variables are measured without error. It is usually more reasonable to assume that you have not measured your set of items perfectly. Although some argue that the two methods have the same results, there is also evidence that factor analysis has better results than PCA (Widaman, 1993). See @russell2002 for a discussion.

**Conclusion**: Do not use PCA.

### Factor Extraction Method

Extraction is the general term for the process of reducing the number of dimensions being analyzed from the number of variables in the data set (and matrix of associations) into a smaller number of factors.

There are multiple factor extract methods, such as:

-   minres

-   unweighted least squares (ULS)

-   generalized least squares (GLS)

-   maximum likelihood

-   principal axis factor(ing)

-   alpha factor(ing)

-   image factor(ing)

It's not entirely clear which factor extraction method is the best and some authors use different terms for some of the methods, making it more difficult to compare them.

Fabrigar, Wegener, MacCallum and Strahan (1999) argued that if data are relatively normally distributed, maximum likelihood is the best choice because "it allows for the computation of a wide range of indexes of the goodness of fit of the model \[and\] permits statistical significance testing of factor loadings and correlations among factors and the computation of confidence intervals." (p. 277). In case the data is not generally normally distributed, they recommend principal axis factoring. This is recommended in several sources (@costello2005, @osborne2014).

**Conclusion**: Use the maximum likelihood method if the data is generally normally distributed and to use principal axis factoring if the data is non-normal.

### Rotation methods

The goal of rotation is to clarify the factor structure and make the results of the EFA more interpretable.

Rotation methods can be categorized into one of two categories: orthogonal or oblique. Orthogonal rotations keep axes at a 90 degree angle, forcing the factors to be uncorrelated. Oblique rotations allow angles that are not 90 degree , thus allowing factors to be correlated if that is optimal for the solution.

Orthogonal rotation methods include:

-   varimax

-   quartimax

-   equamax

Oblique rotation methods include:

-   direct oblimin

-   quartimin

-   promax

In the social sciences, we generally expect some correlation among factors, since behavior is rarely partitioned into neatly packaged units that function independently of one another. Therefore using orthogonal rotation results in a loss of valuable information if the factors are correlated, and oblique rotation should theoretically render a more accurate, and perhaps more reproducible, solution. If the factors are truly uncorrelated, orthogonal and oblique rotation produce nearly identical results. Since oblique rotation will reproduce an orthogonal solution but not vice versa, it makes sense to go for oblique rotation.

There is no widely preferred method of oblique rotation; all tend to produce similar results (Fabrigar et al., 1999).

**Conclusion**: Use any oblique rotation.

### Number of factors to retain

There are several methods to determine how many factors to retain:

-   Theory

-   Kaiser criterion (eigenvalues greater than 1; Kaiser, 1960)

-   Scree test (Cattell, 1966)

-   Parallel analysis (Horn, 1965)

-   Velicer's multiple average partial (MAP) procedure (Velicer, 1976)

-   Akaike information criterion (AIC; Akaike, 1974)

-   Bayesian information criterion (BIC; Schwarz, 1978)

-   Comparison data (CD; @ruscio2012)

-   Very Simple Structure (VSS)

If the theoretical framework for the instrument is sound, we should start with the expectation that we should see that structure in the data. Instruments are rarely perfect (especially the first time it is examined), and theoretical expectations are not always supported. But unless one is on a fishing expedition in a data set with no a priori ideas about how the analysis should turn out, 12 this is as good a place as any to start.

The default in most statistical software packages is to use the Kaiser criterion. It makes some sense, as an eigenvalue represents the sum of the squared factor loadings in a column, and to get a sum of 1.0 or more, one must have rather large factor loadings to square and sum. However, this is easily achieved with more items and there are now alternative methods. Hence, there is broad consensus in the literature that this is among the least accurate methods for selecting the number of factors to retain (Velicer & Jackson, 1990).

The scree test involves examining the graph of the eigenvalues (available via every software package) and looking for the natural bend or "elbow" in the data where the slope of the curve changes (flattens) markedly. Although the scree plot itself is not considered sufficient to determine how many factors should be extracted (Velicer et al., 2000), many suggest that researchers examine solutions extracting the number of factors ranging from one to two factors above the elbow to one or two below.

Parallel analysis involves generating random uncorrelated data, and comparing eigenvalues from the EFA to those eigenvalues from those random data. Using this process, only factors with eigenvalues that are significantly above the mean (or preferably, the 95 th percentile) of those random eigenvalues should be retained. Several prominent authors and journals have endorsed this as the most robust and accurate process for determining the number of factors to extract (Ledesma & Valero-Mora, 2007; Velicer et al., 2000).

The Minimum Average Partial (MAP) criterion involves partialing out common variance as each successive component is created. As each successive component is partialed out, common variance will decrease to a minimum. Velicer argued that minimum point should be considered the criterion for the number of factors to extract.

VSS involves degrading the initial rotated factor solution by **assuming** that the nonsalient loadings are zero, even though in actuality they rarely are. What VSS does is test how well the factor matrix we **think** abaut and talk about actually fits the correlation matrix. It is not a confirmatory procedure for testing the significance of a particular loading, but rather it is an exploratory procedure for testing the relative utility of **interpreting** the correlation matrix in terms of a family of increasingly more complex factor models. The simplest model tasted by VSS is that each item is of complexity one, and that all items are embedded in a more complex factor matrix of rank k. This is the model most appropriate for scale construction and is the one we use most frequently when we talk about factor solutions. More complicated models may also be evaluated by VSS.

Zwick and Velicer (1986) tested the scree test, Horn's parallel test, and Velicer's MAP test (among others) in simulation studies using a data set with a clear factor structure. Both the parallel test and MAP test seemed to work well.

@ruscio2012 notes that PA is considered to be the method of choice among methodologists and recommend that researchers take advantage of PA as a starting point, perhaps supplemented by CD. They note that researchers can also use more than one method. Similarly, several prominent authors and journals have endorsed this as the most robust and accurate process for determining the number of factors to extract (Ledesma & Valero-Mora, 2007; Velicer et al., 2000).

@osborne2014 notes that MAP has been considered superior to the "classic" criteria, and probably is superior to parallel analysis, although neither is perfect, and all must be used in the context of a search for conceptually interpretable factors. He recommends to use parallel analysis or MAP criteria, along with theory (and any of the classic criteria that suits you and is defensible).

**Conclusion:** Use multiple criteria and theory to make a judgment call about how many factors to extract.

### Sample

Make sure to target participants that are likely to vary in the attitude that you're interested in measuring.

Make sure the sample is representative of the population that you're interested in.

### Sample size

#### Rules of thumb

The general consensus seems to be that rules of thumb are a bad idea. The reason for that is that these rules only involve one of two factors. Common rules of thumb consist of going for a set number of participants or a particular participant-to-item ratio.

+--------------------------+-----------------------+--------------------------------+
| Type                     | Source                | Rule                           |
+==========================+=======================+================================+
| *Participant-only*       |                       |                                |
+--------------------------+-----------------------+--------------------------------+
|                          | @comrey1992           | 50 = very poor\                |
|                          |                       | 100 = poor\                    |
|                          |                       | 200 = fair\                    |
|                          |                       | 300 = good\                    |
|                          |                       | 500 = very good\               |
|                          |                       | 1000+ = excellent              |
+--------------------------+-----------------------+--------------------------------+
|                          | Barrett & Kline, 1981 | 50                             |
+--------------------------+-----------------------+--------------------------------+
|                          | Aleamoni, 1976        | 400                            |
+--------------------------+-----------------------+--------------------------------+
|                          |                       |                                |
+--------------------------+-----------------------+--------------------------------+
|                          |                       |                                |
+--------------------------+-----------------------+--------------------------------+
| *Participant:item ratio* |                       |                                |
+--------------------------+-----------------------+--------------------------------+
|                          | @gorsuch2015, p.332   | 5:1 (100 participants minimum) |
+--------------------------+-----------------------+--------------------------------+
|                          | Hatcher 1994, p.73    | 5:1 (minimum)                  |
+--------------------------+-----------------------+--------------------------------+
|                          | @everitt1975          | 10:1 (optimistically)          |
+--------------------------+-----------------------+--------------------------------+
|                          | Nunally (1978), p.421 | 10:1                           |
+--------------------------+-----------------------+--------------------------------+
|                          |                       |                                |
+--------------------------+-----------------------+--------------------------------+
|                          |                       |                                |
+--------------------------+-----------------------+--------------------------------+
|                          |                       |                                |
+--------------------------+-----------------------+--------------------------------+

: Table: Examples of rules of thumb.

The reality is that the sample size is dependent on:

-   the study design (e.g., cross-sectional vs. longitudinal)

-   the size of the relationships among the indicators (e.g., high communalities without cross loadings; strong loadings)

-   the reliability of the indicators

-   the scaling (e.g., categorical, continuous) and distribution of the indicators

-   estimator type (e.g., ML, robust ML, WLSMV)

-   the amount and patterns of missing data

-   the size of the model (model complexity)

For example, MacCallum, Widaman, Zhang, and Hong (1999) found that results were consistent with population loadings with sample sizes as low as 60 cases if the communalities of the items were high (.60 or greater). With lower communality levels (around .50), samples of 100 to 200 cases were required.

Costello and Osborne [-@costello2005] caution researchers to remember that EFA is a large-sample procedure and that generalizable or replicable results are unlikely if the sample is too small. They found that a ratio of 20:1 produces error rates well above the standard alpha (5%) level. They also say that researchers should realize that EFA is exploratory and should be used only for exploring data, not hypothesis or theory testing.

#### Number of indicators

At least three items per factor are required for a factor model to be identified; more items per factor results in overidentification of the model. A number of writers recommend that four or more items per factor be included in the factor analysis to ensure an adequate identification of the factors (Comrey & Lee, 1992; Fabrigar et al., 1999; Gorsuch, 1988).

MacCallum et al. (1999) found that in addition to the communality of the measures, the results were more accurate for given sample sizes if there were more measures per factor included in the analysis.

Some additional arguments for why multiple indicators per factor are useful:

-   People read items incorrectly or sometimes just don't understand an item (despite all efforts to make them as clear as possible), so having a sample of items can counteract the idiosyncratic mistakes of respondents

-   With complicated topics, having multiple items also adds clarity about the overall goal of the scale. Each item is an indicator to the participant about what the purpose of the scale is.

### Sampling Adequacy

The Kaiser--Meyer--Olkin (KMO) test is a statistical measure to determine how suited data is for factor analysis. The test measures sampling adequacy for each variable in the model and the complete model. The statistic is a measure of the proportion of variance among variables that might be common variance. The lower the proportion, the higher the KMO value, the more suited the data is to factor analysis

The KMO value ranges from 0 to 1, with 0.60 considered suitable for factor analysis @tabachnick2013. Kaiser himself [-@kaiser1974] suggested that KMO \> .9 were marvelous, in the .80s, mertitourious, in the .70s, middling, in the .60s, medicore, in the 50s, miserable, and less than .5, unacceptable.

Bartlett's (1954) test of sphericity is a notoriously sensitive test of the hypothesis that the correlations in a correlation matrix are zero. Because of its sensitivity and its dependence on N, the test is likely to be significant with samples of substantial size even if correlations are very low. Therefore, use of the test is recommended only if there are fewer than, say, five cases per variable [@tabachnick2013].

### Outlier removal

Should you remove outliers?

### Factor structure

Tabachnick and Fidell (2001) cite .32 as a good rule of thumb for the minimum loading of an item. Others say item loadings above .30 (Costello).

Others say a factor loading coefficient ≥ 0.40 is considered necessary to judge the quality (validity) of an item as an indicator of one factor or another. Some may think that this criterion is quite lax since a factor loading of 0.40 means that only 16% of the explained variance depends on the factor of which one item is the indicator (Gana & Broc)

Some psychometricians (for example, \[COM 92, TAB 07\]) recommend that we choose items whose R² is greater than 0.40 (thus showing a factorial factor loading greater than 0.63).

-   A "crossloading" item is an item that loads at .32 or higher on two or more factors. The researcher needs to decide whether a crossloading item should be dropped from the analysis, which may be a good choice if there are several adequate to strong loaders (.50 or better) on each factor.

    A factor with fewer than three items is generally weak and unstable; 5 or more strongly loading items (.50 or better) are desirable and indicate a solid factor.

Comrey and Lee (1992) suggest that loadings in excess of .71 (50% overlapping variance) are considered excellent, .63 (40% overlapping variance) very good, .55 (30% overlapping variance) good, .45 (20% overlapping variance) fair, and .32 (10% overlapping variance) poor.

#### Number of indicators to keep

-   , it is important for the latent variable to have at least four indicators (for example: four items). In effect, with only three indicators, the measurement model is just-identified, thus making useless its testability. (Gana & Broc)

### Interpretation

Remember that the goal of exploratory factor analysis is to explore whether your data fits a model that makes sense. Ideally, you have a conceptual or theoretical framework for the analysis- a theory or body of literature guiding the development of an instrument, for example. Even if you do not, the results should be sensible in some way. You should be able to construct a simple narrative describing how each factor, and its constituent variables, makes sense and is easily labeled.

### Additional reading

The summaries and conclusions above were largely taken from the following sources:

-   Best Practices in Exploratory Factor Analysis by @osborne2014

<!-- -->

-   In Search of Underlying Dimensions: The Use (and Abuse) of Factor Analysis in Personality and Social Psychology Bulletin by @russell2002

## Confirmatory factor analysis

For confirmatory factor analyses there are also several ways to determine the sample size, including:

1.  Rules of thumb
2.  Satorra-Saris method
3.  Monte Carlo approach

### Number of indicators

Some argue that when it comes to the number of indicators, more is better @marsh1998.

### Estimator

If the data is normally distributed, use the ML estimator.

the findings of Chou and Bentler \[CHO 95\] make it possible to qualify these remarks. These authors showed that in the presence of a sufficiently large sample, maximum likelihood estimation method and generalized least squares method do not make the results suffer, even when the multivariate normality is slightly violated.

In case of violations, the following estimators can be used:

-   MLM

-   MLR: Similar to MLM but better suited for small sample sizes (Gana & Broc).

-   weighted least squares method (WLS): Requires a large sample size (FLO 04) and frequently runs into convergence issues and improper solutions

-   Diagonally Weighted Least Squares (DWLS): For small samples and non-normal data (\[JÖR 89)

-   WLSM: Robust alternative to DWLS

-   WLSMV: Robust alternative to DWLS

-   bootstrapping: Not recommended for dichotomous and ordinal measures with few response categories)

Mardia calculation to determine violations from normal distribution. It can be noted that not only is this standardized coefficient statistically significant, but its value is greater than 5, which is the threshold value beyond which multivariate normality seems to fail \[KLI 16\].

| Data type and normality assumption | Recommended estimator                            |
|------------------------------------|--------------------------------------------------|
| *Continuous data*                  |                                                  |
| Approximately normal distribution  | ML                                               |
| Violation of normality assumption  | ML (in case of moderate violation)               |
|                                    | MLM, MLR, Bootstrap                              |
| *Ordinal/categorical data*         |                                                  |
| Approximately normal distribution  | ML (if at least 6 response categories)           |
|                                    | MLM, MLR (if at least 4 response categories)     |
|                                    | WLSMV (binary response or 3 response categories) |
| Violation of normality assumption  | ML (if at least 6 response categories)           |
|                                    | MLM, MLR (if at least 4 response categories)     |
|                                    | WLSMV (in case of severe violation)              |

: Recommendations concerning the main estimators available in lavaan according to the type of data (Gana & Broc).

### Fit indices

The only advice we can afford to give, however, is to closely follow developments concerning fit indices. In the meantime, you can carefully follow the recommendations of Hu and Bentler \[HU 99\] or Schreiber and his co-authors \[SCH 06\] who suggest the following guidelines for judging a model goodness-of-fit (based on the hypothesis where the maximum likelihood method is the estimation method): 1) RMSEA value ≤ 0.06, with confidence interval at 90% values should be between 0 and 1.00; 2) SRMR value ≤ 0.08; and 3) CFI and TLI values ≥ 0.95.

+--------------+----------+--------------------------------------------------------------------------+
| Fit Type     | Index    | Benchmark                                                                |
+==============+==========+==========================================================================+
| Absolute     | RMR/SRMR | ≤ 0.08 = good fit                                                        |
+--------------+----------+--------------------------------------------------------------------------+
|              | WRMR     | ≤ 1.00 = good fit                                                        |
+--------------+----------+--------------------------------------------------------------------------+
| Parsimonious | PRATIO   | Between 0.00 (saturated model) and 1.00 (parsimonious model)             |
+--------------+----------+--------------------------------------------------------------------------+
|              | RMSEA    | ≤ 0.05 = very good fit\                                                  |
|              |          | ≤ 0.06 and ≤ 0.08 = good fit                                             |
+--------------+----------+--------------------------------------------------------------------------+
|              | AIC      | Comparative index: the lower value of this index, the better the fit     |
+--------------+----------+--------------------------------------------------------------------------+
|              | BIC      | Comparative index: the lower value of this BIC index, the better the fit |
+--------------+----------+--------------------------------------------------------------------------+
| Incremental  | CFI      | ≥ 0.90 and ≤ 0.94 = good fit\                                            |
|              |          | ≥ 0.95 = very good fit                                                   |
+--------------+----------+--------------------------------------------------------------------------+
|              | TLI      | ≥ 0.90 and ≤ 0.94 = good fit\                                            |
|              |          | ≥ 0.95 = very good fit                                                   |
+--------------+----------+--------------------------------------------------------------------------+

: Fit indices guidance from @gana2019

### Reliability

Reliability increases the closer the value gets to 1.00, with an acceptability threshold of 0.70.

## Examples

-   Beyond Sacrificial Harm: A Two-Dimensional Model of Utilitarian Psychology

## R packages

-   lavaan

-   lavaan.survey

-   semTools

-   semPower

## Useful links

-   <https://stats.idre.ucla.edu/spss/seminars/introduction-to-factor-analysis/a-practical-introduction-to-factor-analysis/>
