# Foldable Sections

Our bookdown template supports foldable sections by means of custom blocks and custom code written specifically by us. Note that this means this feature is not supported out of the box and that some setup is necessary if you start with a fresh install of the `bookdown` format. It is recommended to clone the files of this template so that you don't have to worry about it.

A foldable section can be created by placing text between two sets of three colons (`:::`) and specifying the `.foldable` class between two curly braces, like so:

    ::: {.foldable}
    <button class="fold-button">Show me more</button>
    
    This is a foldable section.
    :::

This creates the following foldable section:

::: foldable
<button class="fold-button">Show me more</button>

This is a foldable section.
:::

By default is shows the "Show me more" text, followed by "Show me less" after clicking on it. This text could be changed to something else in the `header.html` file that can be found in the `assets` folder.

For more information on custom blocks, see [here](https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html).
