# How to use this template

The goal of this template is to make it easy to get started on writing a `bookdown` book. The word 'book' might be a misnomer because you can also use it to write notes, a manual (similar to this bookdown), a thesis, and many other things.

If you have enough time, the best way to get started is to read the `bookdown` [book](https://bookdown.org/yihui/bookdown/). For those in a hurry, we list the important steps below.

## Setup

1.  Clone this template from GitHub. The easiest way to do this is to open RStudio and select File -> New Project -> Version Control -> Git. The repository URL of this template is "<https://github.com/rethinkpriorities/bookdown-template>". After entering this, and changing some of the other settings if you want to, click on Create Project.

2.  Next, go to the Build tab (next to Environment, History, and Connection) and click on "Build Book".

3.  Done. The book is up and running!

## Usage

The template is in and of itself not interesting, so now you need to adapt the content. The first thing to adapt are the contents of 'index.Rmd'. You should change some of the information at the top of the file (between the two `---` symbols). These are the YAML options and you can change them to alter the meta-information of the book or to change some of the settings.

After changing the content of this file, you should start adding chapters. This template comes with a 'chapters' folder where you can store individual chapter files. You can simply take one of the example chapters and change the content. You should also change the file names, but in order for the book to include the chapter when you build it, you should change the contents of `_bookdown.yml`. Make sure to adapt the file paths in the `rmd_files` option so it refers to the new chapter. The order of these file paths also determines the order of the chapters in the book.
