---
title: "Confirmatory Factor Analysis"
---

::: callout-warning
This chapter is still a work in progress.
:::

Note that if you have a clear theoretical basis about the number of factors and which items should load on which factor, CFA is more appropriate than EFA because it allows you to directly test your model. You could also do both, but a CFA should be conducted on new data to test its validity.

For confirmatory factor analyses there are also several ways to determine the sample size, including:

1.  Rules of thumb
2.  Satorra-Saris method
3.  Monte Carlo approach

### Number of indicators

Some argue that when it comes to the number of indicators, more is better @marsh1998.

### Estimator

If the data is normally distributed, use the ML estimator.

the findings of Chou and Bentler make it possible to qualify these remarks. These authors showed that in the presence of a sufficiently large sample, maximum likelihood estimation method and generalized least squares method do not make the results suffer, even when the multivariate normality is slightly violated.

In case of violations, the following estimators can be used:

-   MLM

-   MLR: Similar to MLM but better suited for small sample sizes (Gana & Broc).

-   weighted least squares method (WLS): Requires a large sample size (FLO 04) and frequently runs into convergence issues and improper solutions

-   Diagonally Weighted Least Squares (DWLS): For small samples and non-normal data (\[JÖR 89)

-   WLSM: Robust alternative to DWLS

-   WLSMV: Robust alternative to DWLS

-   bootstrapping: Not recommended for dichotomous and ordinal measures with few response categories)

Mardia calculation to determine violations from normal distribution. It can be noted that not only is this standardized coefficient statistically significant, but its value is greater than 5, which is the threshold value beyond which multivariate normality seems to fail.

+------------------------------------+--------------------------------------------------+
| Data type and normality assumption | Recommended estimator                            |
+====================================+==================================================+
| *Continuous data*                  |                                                  |
+------------------------------------+--------------------------------------------------+
| Approximately normal distribution  | ML                                               |
+------------------------------------+--------------------------------------------------+
| Violation of normality assumption  | ML (in case of moderate violation)               |
+------------------------------------+--------------------------------------------------+
|                                    | MLM, MLR, Bootstrap                              |
+------------------------------------+--------------------------------------------------+
| *Ordinal/categorical data*         |                                                  |
+------------------------------------+--------------------------------------------------+
| Approximately normal distribution  | ML (if at least 6 response categories)           |
+------------------------------------+--------------------------------------------------+
|                                    | MLM, MLR (if at least 4 response categories)     |
+------------------------------------+--------------------------------------------------+
|                                    | WLSMV (binary response or 3 response categories) |
+------------------------------------+--------------------------------------------------+
| Violation of normality assumption  | ML (if at least 6 response categories)           |
+------------------------------------+--------------------------------------------------+
|                                    | MLM, MLR (if at least 4 response categories)     |
+------------------------------------+--------------------------------------------------+
|                                    | WLSMV (in case of severe violation)              |
+------------------------------------+--------------------------------------------------+

: Recommendations concerning the main estimators available in lavaan according to the type of data (Gana & Broc).

### Fit indices

The only advice we can afford to give, however, is to closely follow developments concerning fit indices. In the meantime, you can carefully follow the recommendations of Hu and Bentler or Schreiber and his co-authors who suggest the following guidelines for judging a model goodness-of-fit (based on the hypothesis where the maximum likelihood method is the estimation method): 1) RMSEA value ≤ 0.06, with confidence interval at 90% values should be between 0 and 1.00; 2) SRMR value ≤ 0.08; and 3) CFI and TLI values ≥ 0.95.

+--------------+-----------+--------------------------------------------------------------------------+
| Fit Type     | Index     | Benchmark                                                                |
+==============+===========+==========================================================================+
| Absolute     | RMR/SRMR  | ≤ 0.08 = good fit                                                        |
+--------------+-----------+--------------------------------------------------------------------------+
|              | WRMR      | ≤ 1.00 = good fit                                                        |
+--------------+-----------+--------------------------------------------------------------------------+
| Parsimonious | PRATIO    | Between 0.00 (saturated model) and 1.00 (parsimonious model)             |
+--------------+-----------+--------------------------------------------------------------------------+
|              | RMSEA     | ≤ 0.05 = very good fit\                                                  |
|              |           | ≤ 0.06 and ≤ 0.08 = good fit                                             |
+--------------+-----------+--------------------------------------------------------------------------+
|              | AIC       | Comparative index: the lower value of this index, the better the fit     |
+--------------+-----------+--------------------------------------------------------------------------+
|              | BIC       | Comparative index: the lower value of this BIC index, the better the fit |
+--------------+-----------+--------------------------------------------------------------------------+
| Incremental  | CFI       | ≥ 0.90 and ≤ 0.94 = good fit\                                            |
|              |           | ≥ 0.95 = very good fit                                                   |
+--------------+-----------+--------------------------------------------------------------------------+
|              | TLI       | ≥ 0.90 and ≤ 0.94 = good fit\                                            |
|              |           | ≥ 0.95 = very good fit                                                   |
+--------------+-----------+--------------------------------------------------------------------------+

: Fit indices guidance from @gana2019

### Reliability

Reliability increases the closer the value gets to 1.00, with an acceptability threshold of 0.70.

## Recommended Reading

-   Dynamic Fit Index Cutoffs for Confirmatory Factor Analysis Models by @mcneish2021
